import { motion } from "framer-motion";
import {
  Sparkles, CheckCircle2, FileText, CalendarDays, AtSign, Briefcase,
} from "lucide-react";
import "./dashboard.css";
import Navbar                  from "../Navbar";
import SummaryCards            from "./SummaryCards";
import ATSScore                from "./ATSScore";
import GithubAnalysis          from "./GithubAnalysis";
import StrengthCards           from "./StrengthCards";
import SkillGap                from "./SkillGap";
import ImprovementTimeline     from "./ImprovementTimeline";
import CareerRoadmap           from "./CareerRoadmap";
import LearningRecommendations from "./LearningRecommendations";
import ReportSection           from "./ReportSection";
import ActionBar               from "./ActionBar";
/* Job-mode-only components */
import JobMatchScore           from "./JobMatchScore";
import JobMatchCards           from "./JobMatchCards";
import MissingKeywords         from "./MissingKeywords";
import JobResumeChanges        from "./JobResumeChanges";
import InterviewQuestions      from "./InterviewQuestions";
import ApplyRecommendation     from "./ApplyRecommendation";
import JobRoadmap              from "./JobRoadmap";

export default function Dashboard({ data, onReset }) {
  const isJobMode = data.mode === "job";

  return (
    <div className="db-shell">
      <Navbar />

      {/* ── Hero ── */}
      <motion.div
        className="db-hero"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
      >
        <div className="db-hero-top">
          <div>
            <motion.div
              className="db-hero-badge"
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
            >
              <CheckCircle2 size={11} strokeWidth={2.5} />
              Analyzed Successfully
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.15 }}
            >
              {isJobMode ? "Job Match Report" : "Career Intelligence Report"}
            </motion.h1>

            <motion.p
              className="db-hero-sub"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
            >
              {isJobMode ? "Job Match Analysis by CareerPilot AI" : "Generated by CareerPilot AI"}
              <span style={{ marginLeft: "10px", display: "inline-flex", alignItems: "center", gap: "4px", color: "var(--indigo-hi)" }}>
                <Sparkles size={11} strokeWidth={2.5} />
                {isJobMode ? "Job Mode" : "Profile Mode"}
              </span>
            </motion.p>
          </div>
        </div>

        <motion.div
          className="db-hero-meta"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.25 }}
        >
          <div className="db-meta-item">
            <FileText size={13} />
            <strong>{data.fileName || "Resume"}</strong>
          </div>
          <div className="db-meta-item">
            <AtSign size={13} />
            <strong>{data.githubUsername}</strong>
          </div>
          {isJobMode && data.jobDescription && (
            <div className="db-meta-item">
              <Briefcase size={13} />
              <strong>
                {data.jobDescription.length > 40
                  ? data.jobDescription.slice(0, 40) + "…"
                  : data.jobDescription}
              </strong>
            </div>
          )}
          <div className="db-meta-item">
            <CalendarDays size={13} />
            <strong>{data.analyzedAt}</strong>
          </div>
        </motion.div>
      </motion.div>

      {/* ── Dashboard body ── */}
      <div className="db-main">

        {/* ── JOB MODE: extra sections at the top ── */}
        {isJobMode && (
          <>
            {/* Job match hero card — full width */}
            <JobMatchScore data={data} />

            {/* Match breakdown + Apply recommendation */}
            <div className="db-grid-2">
              <JobMatchCards data={data} />
              <ApplyRecommendation data={data} />
            </div>

            {/* Missing keywords & skills */}
            <MissingKeywords data={data} />
          </>
        )}

        {/* ── SHARED: existing dashboard sections ── */}
        <SummaryCards data={data} />

        <div className="db-grid-2">
          <ATSScore       atsText={data.ats_analysis} />
          <GithubAnalysis ghText={data.github_analysis} />
        </div>

        <StrengthCards
          atsText={data.ats_analysis}
          careerText={data.career_report}
        />

        <SkillGap atsText={data.ats_analysis} />

        <div className="db-grid-2">
          {/* Job mode: job-specific resume changes; Profile mode: generic improvements */}
          {isJobMode
            ? <JobResumeChanges data={data} />
            : <ImprovementTimeline improvedText={data.improved_resume} />
          }
          {/* Job mode: job roadmap; Profile mode: career roadmap */}
          {isJobMode
            ? <JobRoadmap data={data} />
            : <CareerRoadmap careerText={data.career_report} />
          }
        </div>

        {/* ── JOB MODE: interview prep ── */}
        {isJobMode && (
          <InterviewQuestions data={data} />
        )}

        <LearningRecommendations careerText={data.career_report} />

        <ReportSection careerReport={data.career_report} />

      </div>

      <ActionBar data={data} onReset={onReset} />
    </div>
  );
}
